export const REGIONS_DATA: Record<number, { name: string; districts: { id: number; name: string }[] }> = {
    1: {
        name: 'Toshkent shahri',
        districts: [
            { id: 1, name: 'Bektemir tumani' },
            { id: 2, name: 'Chilonzor tumani' },
            { id: 3, name: 'Mirobod tumani' },
            { id: 4, name: 'Mirzo Ulug\'bek tumani' },
            { id: 5, name: 'Olmazor tumani' },
            { id: 6, name: 'Sergeli tumani' },
            { id: 7, name: 'Shayxontohur tumani' },
            { id: 8, name: 'Yashnobod tumani' },
            { id: 9, name: 'Uchtepa tumani' },
            { id: 10, name: 'Yunusobod tumani' },
            { id: 11, name: 'Yangi hayot tumani' },
        ],
    },
    2: {
        name: 'Toshkent viloyati',
        districts: [
            { id: 1, name: 'Bekobod tumani' },
            { id: 2, name: 'Bo\'ka tumani' },
            { id: 3, name: 'Bo\'stonliq tumani' },
            { id: 4, name: 'Zangiota tumani' },
            { id: 5, name: 'Qibray tumani' },
            { id: 6, name: 'Quyichirchiq tumani' },
            { id: 7, name: 'Oqqo\'rg\'on tumani' },
            { id: 8, name: 'Olmaliq shahri' },
            { id: 9, name: 'Ohangaron tumani' },
            { id: 10, name: 'Parkent tumani' },
            { id: 11, name: 'Piskent tumani' },
            { id: 12, name: 'Toshkent tumani' },
            { id: 13, name: 'Yuqorichirchiq tumani' },
            { id: 14, name: 'Chinoz tumani' },
            { id: 15, name: 'Yangiyo\'l tumani' },
            { id: 16, name: 'Angren shahri' },
        ],
    },
    3: {
        name: 'Samarqand viloyati',
        districts: [
            { id: 1, name: 'Bulung\'ur tumani' },
            { id: 2, name: 'Ishtixon tumani' },
            { id: 3, name: 'Jomboy tumani' },
            { id: 4, name: 'Kattaqo\'rg\'on tumani' },
            { id: 5, name: 'Kattaqo\'rg\'on shahri' },
            { id: 6, name: 'Narpay tumani' },
            { id: 7, name: 'Nurobod tumani' },
            { id: 8, name: 'Oqdaryo tumani' },
            { id: 9, name: 'Pastdarg\'om tumani' },
            { id: 10, name: 'Paxtachi tumani' },
            { id: 11, name: 'Samarqand tumani' },
            { id: 12, name: 'Samarqand shahri' },
            { id: 13, name: 'Tayloq tumani' },
            { id: 14, name: 'Urgut tumani' },
            { id: 15, name: 'Toyloq tumani' },
            { id: 16, name: 'Qo\'shrabot tumani' },
        ],
    },
    4: {
        name: 'Andijon viloyati',
        districts: [
            { id: 1, name: 'Andijon tumani' },
            { id: 2, name: 'Andijon shahri' },
            { id: 3, name: 'Asaka tumani' },
            { id: 4, name: 'Baliqchi tumani' },
            { id: 5, name: 'Bo\'z tumani' },
            { id: 6, name: 'Buloqboshi tumani' },
            { id: 7, name: 'Izboskan tumani' },
            { id: 8, name: 'Jalaquduq tumani' },
            { id: 9, name: 'Marhamat tumani' },
            { id: 10, name: 'Oltinko\'l tumani' },
            { id: 11, name: 'Paxtaobod tumani' },
            { id: 12, name: 'Qorasuv shahri' },
            { id: 13, name: 'Qo\'rg\'ontepa tumani' },
            { id: 14, name: 'Shahrixon tumani' },
            { id: 15, name: 'Ulug\'nor tumani' },
            { id: 16, name: 'Xo\'jaobod tumani' },
            { id: 17, name: 'Xonobod shahri' },
        ],
    },
    5: {
        name: 'Buxoro viloyati',
        districts: [
            { id: 1, name: 'Buxoro tumani' },
            { id: 2, name: 'Buxoro shahri' },
            { id: 3, name: 'G\'ijduvon tumani' },
            { id: 4, name: 'Jondor tumani' },
            { id: 5, name: 'Kogon tumani' },
            { id: 6, name: 'Kogon shahri' },
            { id: 7, name: 'Olot tumani' },
            { id: 8, name: 'Peshku tumani' },
            { id: 9, name: 'Qorako\'l tumani' },
            { id: 10, name: 'Qorovulbozor tumani' },
            { id: 11, name: 'Romitan tumani' },
            { id: 12, name: 'Shofirkon tumani' },
            { id: 13, name: 'Vobkent tumani' },
        ],
    },
    6: {
        name: 'Farg\'ona viloyati',
        districts: [
            { id: 1, name: 'Bag\'dod tumani' },
            { id: 2, name: 'Beshariq tumani' },
            { id: 3, name: 'Buvayda tumani' },
            { id: 4, name: 'Dang\'ara tumani' },
            { id: 5, name: 'Farg\'ona tumani' },
            { id: 6, name: 'Farg\'ona shahri' },
            { id: 7, name: 'Furqat tumani' },
            { id: 8, name: 'Marg\'ilon shahri' },
            { id: 9, name: 'Oltiariq tumani' },
            { id: 10, name: 'Qo\'qon shahri' },
            { id: 11, name: 'Qo\'shtepa tumani' },
            { id: 12, name: 'Quva tumani' },
            { id: 13, name: 'Quvasoy shahri' },
            { id: 14, name: 'Rishton tumani' },
            { id: 15, name: 'So\'x tumani' },
            { id: 16, name: 'Toshloq tumani' },
            { id: 17, name: 'Uchko\'prik tumani' },
            { id: 18, name: 'Yozyovon tumani' },
        ],
    },
    7: {
        name: 'Jizzax viloyati',
        districts: [
            { id: 1, name: 'Arnasoy tumani' },
            { id: 2, name: 'Baxmal tumani' },
            { id: 3, name: 'Dostlik tumani' },
            { id: 4, name: 'Forish tumani' },
            { id: 5, name: 'G\'allaorol tumani' },
            { id: 6, name: 'Jizzax shahri' },
            { id: 7, name: 'Sharof Rashidov tumani' },
            { id: 8, name: 'Mirzacho\'l tumani' },
            { id: 9, name: 'Paxtakor tumani' },
            { id: 10, name: 'Yangiobod tumani' },
            { id: 11, name: 'Zomin tumani' },
            { id: 12, name: 'Zafarobod tumani' },
            { id: 13, name: 'Zarbdor tumani' },
        ],
    },
    8: {
        name: 'Xorazm viloyati',
        districts: [
            { id: 1, name: 'Bog\'ot tumani' },
            { id: 2, name: 'Gurlan tumani' },
            { id: 3, name: 'Qo\'shko\'pir tumani' },
            { id: 4, name: 'Shovot tumani' },
            { id: 5, name: 'Urganch tumani' },
            { id: 6, name: 'Urganch shahri' },
            { id: 7, name: 'Xiva tumani' },
            { id: 8, name: 'Xiva shahri' },
            { id: 9, name: 'Xonqa tumani' },
            { id: 10, name: 'Xazorasp tumani' },
            { id: 11, name: 'Yangiariq tumani' },
            { id: 12, name: 'Yangibozor tumani' },
            { id: 13, name: 'Tuproqqal\'a tumani' },
        ],
    },
    9: {
        name: 'Namangan viloyati',
        districts: [
            { id: 1, name: 'Chortoq tumani' },
            { id: 2, name: 'Chust tumani' },
            { id: 3, name: 'Kosonsoy tumani' },
            { id: 4, name: 'Mingbuloq tumani' },
            { id: 5, name: 'Namangan tumani' },
            { id: 6, name: 'Namangan shahri' },
            { id: 7, name: 'Norin tumani' },
            { id: 8, name: 'Pop tumani' },
            { id: 9, name: 'To\'raqo\'rg\'on tumani' },
            { id: 10, name: 'Uchqo\'rg\'on tumani' },
            { id: 11, name: 'Uychi tumani' },
            { id: 12, name: 'Yangiqo\'rg\'on tumani' },
            { id: 13, name: 'Davlatobod tumani' },
        ],
    },
    10: {
        name: 'Navoiy viloyati',
        districts: [
            { id: 1, name: 'Karmana tumani' },
            { id: 2, name: 'Konimex tumani' },
            { id: 3, name: 'Navbahor tumani' },
            { id: 4, name: 'Navoiy shahri' },
            { id: 5, name: 'Nurota tumani' },
            { id: 6, name: 'Qiziltepa tumani' },
            { id: 7, name: 'Tomdi tumani' },
            { id: 8, name: 'Uchquduq tumani' },
            { id: 9, name: 'Xatirchi tumani' },
            { id: 10, name: 'Zarafshon shahri' },
        ],
    },
    11: {
        name: 'Qashqadaryo viloyati',
        districts: [
            { id: 1, name: 'Chiroqchi tumani' },
            { id: 2, name: 'Dehqonobod tumani' },
            { id: 3, name: 'G\'uzor tumani' },
            { id: 4, name: 'Kasbi tumani' },
            { id: 5, name: 'Kitob tumani' },
            { id: 6, name: 'Qamashi tumani' },
            { id: 7, name: 'Qarshi tumani' },
            { id: 8, name: 'Qarshi shahri' },
            { id: 9, name: 'Mirishkor tumani' },
            { id: 10, name: 'Muborak tumani' },
            { id: 11, name: 'Nishon tumani' },
            { id: 12, name: 'Shahrisabz tumani' },
            { id: 13, name: 'Shahrisabz shahri' },
            { id: 14, name: 'Yakkabog\' tumani' },
        ],
    },
    12: {
        name: 'Qoraqalpog\'iston Respublikasi',
        districts: [
            { id: 1, name: 'Amudaryo tumani' },
            { id: 2, name: 'Beruniy tumani' },
            { id: 3, name: 'Chimboy tumani' },
            { id: 4, name: 'Ellikqal\'a tumani' },
            { id: 5, name: 'Kegeyli tumani' },
            { id: 6, name: 'Mo\'ynoq tumani' },
            { id: 7, name: 'Nukus tumani' },
            { id: 8, name: 'Nukus shahri' },
            { id: 9, name: 'Qanliko\'l tumani' },
            { id: 10, name: 'Qorao\'zak tumani' },
            { id: 11, name: 'Qo\'ng\'irot tumani' },
            { id: 12, name: 'Shumanay tumani' },
            { id: 13, name: 'Taxtako\'pir tumani' },
            { id: 14, name: 'To\'rtko\'l tumani' },
            { id: 15, name: 'Xo\'jayli tumani' },
            { id: 16, name: 'Taxiatosh tumani' },
        ],
    },
    13: {
        name: 'Surxondaryo viloyati',
        districts: [
            { id: 1, name: 'Angor tumani' },
            { id: 2, name: 'Boysun tumani' },
            { id: 3, name: 'Denov tumani' },
            { id: 4, name: 'Jarqo\'rg\'on tumani' },
            { id: 5, name: 'Muzrabot tumani' },
            { id: 6, name: 'Oltinsoy tumani' },
            { id: 7, name: 'Sariosiyo tumani' },
            { id: 8, name: 'Sherobod tumani' },
            { id: 9, name: 'Sho\'rchi tumani' },
            { id: 10, name: 'Termiz tumani' },
            { id: 11, name: 'Termiz shahri' },
            { id: 12, name: 'Uzun tumani' },
            { id: 13, name: 'Qiziriq tumani' },
        ],
    },
    14: {
        name: 'Sirdaryo viloyati',
        districts: [
            { id: 1, name: 'Boyovut tumani' },
            { id: 2, name: 'Guliston tumani' },
            { id: 3, name: 'Guliston shahri' },
            { id: 4, name: 'Oqoltin tumani' },
            { id: 5, name: 'Sardoba tumani' },
            { id: 6, name: 'Sayxunobod tumani' },
            { id: 7, name: 'Sirdaryo tumani' },
            { id: 8, name: 'Shirin shahri' },
            { id: 9, name: 'Xovos tumani' },
            { id: 10, name: 'Yangiobod tumani' },
        ],
    },
};